sudo: false

language: python

python:
  - 3.5

before_install:
  - "pip install -U pip"
  - "python $DATA_GATHER_FOLDER/setup.py install"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)/$DATA_GATHER_FOLDER"

install:
  - pip install -r $DATA_GATHER_FOLDER/requirements.txt

script:

  - flake8 $DATA_GATHER_FOLDER/ 
  - coverage run -m unittest discover -s $DATA_GATHER_FOLDER/tests/ -v

after_success:
  - codecov

notifications:
  email: never