data_gather_folder: IEX\ StockMarket\ Data\ Gathering

sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r {{data_gather_folder}}/requirements.txt

script:
  - flake8 {{data_gather_folder}}/ 
  - python -m unittest discover -s {{data_gather_folder}}/tests/unit -v
  - python -m unittest discover -s {{data_gather_folder}}/tests/integration -v

after_success:
  - codecov
