language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
- TRAVIS_TAG="v1.0" PROJECT_NAME="Project BlackHole" UNITY_PROJECT_PATH="BlackHole"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./travis-build/*.sh

install:
- cat /etc/hosts
- ./travis-build/install-unity.sh

script:
- ./travis-build/build.sh
- ./travis-build/run-tests.sh

after_success:
- ./travis-build/export-unity-package.sh

deploy:
  provider: releases
  api_key: "3a1a4e6e2d71804964c1068db785e14c2d9e483b"
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 

notifications:
  email: never