sudo: false

language: python

python:
  - 3.5

install:
  - pip install -r IEX\ StockMarket\ Data\ Gathering/requirements.txt

script:
  - flake8 IEX\ StockMarket\ Data\ Gathering/ 
  - python -m unittest discover -s tests/unit -v
  - python -m unittest discover -s tests/integration -v

after_success:
  - codecov
